[package]
name = "rockzombot2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "5.0.0"
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }

